### ISSUE TITLE
excelcy installation  failure

### ISSUE THREAD

**Issue by movilla1976** [kororo/excelcy#10]
After pip install excelcy, installation fails with this messages:

Collecting excelcy
  Using cached https://files.pythonhosted.org/packages/fd/9a/f9d71688140e24c15f205f4d6ed798c59aaeae286eb210fa41693b72fe4f/excelcy-0.3.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-XpLl6b/excelcy/setup.py", line 6
        def get_requirements(r: str):
                              ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-XpLl6b/excelcy/

**Comment by kororo** [comment]
@movilla1976 hi, do you mind to do:
```bash
python --version
```
At the moment, I am targeting only python 3.5 and above.
