### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by m-marina** [kororo/excelcy#13]
from excelcy import ExcelCy
excelcy = ExcelCy.execute(file_path="arctic_test_train.xlsx")

[arctic_test_train.xlsx](https://github.com/kororo/excelcy/files/3304918/arctic_test_train.xlsx)

When I run this code, this error occurs:

Traceback (most recent call last):
  File "/tmp/zeppelin_python-6707664677494275063.py", line 312, in <module>
    exec(code, _zcUserQueryNameSpace)
  File "<stdin>", line 7, in <module>
  File "/usr/local/lib/python3.6/dist-packages/excelcy/excelcy.py", line 40, in execute
    fno(**phase.args)
  File "/usr/local/lib/python3.6/dist-packages/excelcy/excelcy.py", line 220, in train
    offset = gold.offset.replace(' ', '').strip()
AttributeError: 'NoneType' object has no attribute 'replace'

Thanks

**Comment by m-marina** [comment]
We changed these 2 conditions in lines 216 and 218, and it worked.

216  if gold.offset is None:
...
218  if offset != -1 or gold.offset is None:

Are we doing right?
