### ISSUE TITLE
duplicate argument 'items' in function definition

### ISSUE THREAD

**Issue by jeronimo13** [kororo/excelcy#7]
I've tried this code snippet
```
from excelcy import ExcelCy
# collect sentences, annotate Entities and train NER using spaCy
excelcy = ExcelCy.execute(file_path='https://github.com/kororo/excelcy/raw/master/tests/data/test_data_01.xlsx')
# use the nlp object as per spaCy API
doc = excelcy.nlp('Google rebrands its business apps')
# or save it for faster bootstrap for application
excelcy.nlp.to_disk('/model')
```

And got this:
```
Traceback (most recent call last):
  File "/Users/herman/Documents/work/ner/excelsy_text.py", line 1, in <module>
    from excelcy import ExcelCy
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/excelcy/__init__.py", line 1, in <module>
    from excelcy.excelcy import ExcelCy
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/excelcy/excelcy.py", line 7, in <module>
    from excelcy.storage import Storage, Source, Prepare, Train
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/excelcy/storage.py", line 55, in <module>
    class Phases(BaseItemListRegistry):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/attr/_make.py", line 364, in wrap
    cls = _add_init(cls, effectively_frozen)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/attr/_make.py", line 569, in _add_init
    bytecode = compile(script, unique_filename, "exec")
  File "<attrs generated init a70e29da20181d24281432341b9ba250b03451c6>", line 1
SyntaxError: duplicate argument 'items' in function definition
```

Python 3.6.2

**Comment by kororo** [comment]
hi @jeronimo13,

I tried to replicate your issue. I cant get the same issue like yours.

I googled around, I found this: https://github.com/python-attrs/attrs/issues/33

Possibly you have old version of attrs?

Can you do pip freeze for me? This is mine. I added hotfix, I realised I dont have attrs in my deps.

```
attrs==18.1.0
certifi==2018.4.16
chardet==3.0.4
cymem==1.31.2
cytoolz==0.9.0.1
dill==0.2.8.2
en-core-web-sm==2.0.0
et-xmlfile==1.0.1
excelcy==0.3.1
idna==2.7
jdcal==1.4
lml==0.0.1
msgpack==0.5.6
msgpack-numpy==0.4.3.1
murmurhash==0.28.0
numpy==1.15.0
openpyxl==2.5.5
plac==0.9.6
preshed==1.0.1
pyexcel==0.5.8
pyexcel-io==0.5.7
pyexcel-xlsx==0.5.6
PyYAML==3.13
regex==2017.4.5
requests==2.19.1
six==1.11.0
spacy==2.0.12
texttable==1.4.0
thinc==6.10.3
toolz==0.9.0
tqdm==4.24.0
ujson==1.35
urllib3==1.23
wrapt==1.10.11
```

**Comment by kororo** [comment]
Ok it is in version 0.3.2 https://github.com/kororo/excelcy/commit/069b5b00fd440abec0f52038de22154dc0d45330

Thanks for testing out the project, let me know if you need more features. I am going to add more pre-processing features such as stopwords.

**Comment by jeronimo13** [comment]
Hola!
I had attrs-17.2.0, upgraded it to attrs-18.1.0 and it automagically worked out! Thanks for the help and sorry for hassle

**Comment by kororo** [comment]
@jeronimo13, please don't be sorry, it is good that you pointed out this issue. I realised I forgot to update requirements :)

Let me know how it goes about the repo, any feedbacks and suggestions are welcomed.

Closing this issue now.
